// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject4
{
    internal sealed partial class Vsix
    {
        public const string Id = "27bf0bda-a4e6-431c-a350-f38a7b74bbf6";
        public const string Name = "ResX Helper 2022";
        public const string Description = @"Adds a right click menu to solution explorer nodes where you can select a base filename or folder. Once you click Add resources the corresponding .resx files will be created with selected in Options locales.";
        public const string Language = "en-US";
        public const string Version = "1.3.28";
        public const string Author = "BDSoftware";
        public const string Tags = "";
    }
}
